theme: jekyll-theme-slate
plugins:
 - jemoji
title: Modern Snakes & Ladders (PF PROJECT)
show_downloads: true
baseurl: /ModernSnakesAndLadders-PF_PROJECT
#include:
#- _layouts
#- _includes
#- assets/css/style.scss
