theme: jekyll-theme-cayman
plugins:
 - jemoji
title: Modern Snakes & Ladders (PF PROJECT)
show_downloads: true
# baseurl: /ModernSnakesAndLadders-PF_PROJECT
exclude:
- _layouts
- _includes
- assets/css/style.scss
